services:
  web:
    image: ghcr.io/ztirom45/guess_number_server:latest
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: db
    ports:
      - "5432:5432"
