name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build jar with gradle
      run: | 
        ./gradlew bootJar 
    - name: Build the server Docker image
      run: | 
        docker build . --tag ghcr.io/ztirom45/guess_number_server:latest
    - name: push to dhcr
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u Ztirom45 --password-stdin
        docker push ghcr.io/ztirom45/guess_number_server:latest

