name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build jar with gradle
      run: | 
        ./gradlew bootJar
    
    - name: Build Compose Images
      run: docker compose -f compose.yaml build
  
    - name: Push image to Container Registry
      run: docker compose -f compose.yaml push

